services:
  api:
    build: .
    image: mini-payment-gateway-proxy:latest
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    env_file:
      - .env
  # Example reverse proxy (optional). Uncomment to use.
  # proxy:
  #   image: nginx:alpine
  #   volumes:
  #     - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - api
